// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfQyBWsWDAjiwDYVEVvzaZ8njqgE50a5k',
    appId: '1:234034167846:web:6329cc64b4245cb70626e7',
    messagingSenderId: '234034167846',
    projectId: 'propsoweb',
    authDomain: 'propsoweb.firebaseapp.com',
    storageBucket: 'propsoweb.appspot.com',
    measurementId: 'G-0MVMV4ETE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB97IlRY7c7IL9SKUKcL3D48g7aQVT9j08',
    appId: '1:234034167846:android:3452f8334d11ea290626e7',
    messagingSenderId: '234034167846',
    projectId: 'propsoweb',
    storageBucket: 'propsoweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALOl757GijaqO9AkgMP1YMqZtzPWBe6hk',
    appId: '1:234034167846:ios:50c356de865c0f790626e7',
    messagingSenderId: '234034167846',
    projectId: 'propsoweb',
    storageBucket: 'propsoweb.appspot.com',
    iosBundleId: 'com.propertycp.customer.propertycpCustomer',
  );
}
