name: propertycp_customer
description: "Search property easily!"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  awesome_dialog: ^3.1.0
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  dropdown_button2: ^2.3.9
  easy_autocomplete: ^1.6.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flashy_tab_bar2: ^0.0.6
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.9
  gallery_image_viewer: ^1.2.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.5
  intl: ^0.19.0
  introduction_screen: ^3.1.12
  line_awesome_flutter: ^2.0.0
  otp_text_field: ^1.1.3
  path_provider: ^2.1.1
  pdf: ^3.10.7
  pod_player: ^0.2.1
  printing: ^5.11.1
  provider: ^6.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  sn_progress_dialog: ^1.1.3
  string_validator: ^1.0.2
  timeago: ^3.2.2
  url_launcher: ^6.2.2
  video_thumbnail: ^0.5.3
  whatsapp_share: ^2.0.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/svgs/
    - assets/banners/

flutter_native_splash:
  image: assets/logos/splash.png
  color: "#ffffff"
  android_12:
    image: assets/logos/logo.png
    color: "#ffffff"
  web_image_mode: center
  android_gravity: fill
  ios_content_mode: scaleToFill
# flutter pub run flutter_native_splash:create
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/logo.png"
  adaptive_icon_background: "#ffffff"
